'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Disc3,Network,Plus,Link2} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {projects,type Project} from './projects';
import {ProjectPreview,projectPreviews} from './project-preview';

const jackets=[
 {title:'Making the call.',sub:'Models meet an audience',color:'#bfd653',ink:'#16231d',image:'tennis.jpg'},
 {title:'People, in sync.',sub:'A working admissions platform',color:'#b8d6cb',ink:'#173c36',image:'whetstone.png'},
 {title:'Nothing lost.',sub:'A home for saved ideas',color:'#c6b8e1',ink:'#382454'},
 {title:'Hello, possibility.',sub:'The work behind a partnership',color:'#ecb5c4',ink:'#61283f'},
 {title:'Show your working.',sub:'Questions with evidence',color:'#adcbea',ink:'#143950'},
 {title:'Room for doubt.',sub:'Decisions without false precision',color:'#e4cf8a',ink:'#584021',image:'admira.jpg'},
];
const connections=[
 {a:0,b:4,label:'Forecasting → evidence',why:'Athena.ai turns model output into stories. Football AI Pro asks what evidence an answer should carry.'},
 {a:4,b:5,label:'Evidence → uncertainty',why:'Football AI Pro makes supporting data inspectable. Admira makes the limits of that data visible.'},
 {a:1,b:5,label:'Operations → decisions',why:'Whetstone starts with the daily admissions workflow. Admira explores how to support a decision within it.'},
 {a:0,b:3,label:'Audience → partnerships',why:'Building an audience and researching creator partnerships both depend on understanding who a story is for.'},
 {a:2,b:3,label:'Ideas → outreach',why:'Spool helps retain useful ideas. Mira brings creator context into partnership research and drafting.'},
 {a:1,b:2,label:'Friction → useful tools',why:'Whetstone and Spool both begin with ordinary tasks that get harder when information is scattered.'},
];
const points=[[22,20],[78,20],[17,73],[50,85],[50,12],[83,73]];
function WorkflowArt({index}:{index:number}){return <div className={`workflow-art art-${index}`} aria-hidden="true"><svg viewBox="0 0 600 340" fill="none"><ellipse cx="300" cy="170" rx="178" ry="92"/><ellipse cx="300" cy="170" rx="92" ry="145" transform="rotate(48 300 170)"/><path d="M105 170H495M300 30V310" strokeDasharray="3 9"/>{[[122,170],[300,78],[478,170],[300,262]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r={i===3?24:17}/><circle cx={x} cy={y} r="5" fill="currentColor"/></g>)}</svg><span>{index===2?'CAPTURE / CONNECT / RECALL':index===3?'CONTEXT / VOICE / CONNECTION':'QUESTION / DATA / EVIDENCE'}</span></div>}
function Story({p}:{p:Project}){return <Dialog><DialogTrigger className="cinema-story-link">The full story <Plus size={18}/></DialogTrigger><DialogContent className="project-dialog"><span className="eyebrow">PROJECT NOTES / {p.name.toUpperCase()}</span><DialogTitle className="dossier-title">{p.headline}</DialogTitle><DialogDescription className="dossier-deck">{p.summary}</DialogDescription><div className="dossier-sections">{[['The problem',p.problem],['What I built',p.built],['The decision that matters',p.decision],['What the evidence supports',p.boundary]].map(([title,text],i)=><section className={i===3?'evidence-note':''} key={title}><h4>{title}</h4><p>{text}</p></section>)}</div><div className="stack-list">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="dossier-links">{p.links.map(l=><a key={l.url} href={l.url} target="_blank" rel="noreferrer">{l.label}<ArrowUpRight size={16}/></a>)}</div></DialogContent></Dialog>}

export default function CinemaWork(){
 const [selected,setSelected]=useState(0);const [map,setMap]=useState(false);const [keyboard,setKeyboard]=useState(false);const shelf=useRef<HTMLDivElement>(null);
 const [shareStatus,setShareStatus]=useState('');
 useEffect(()=>{const requested=new URLSearchParams(location.search).get('project');const index=projects.findIndex(p=>p.id===requested);if(index>=0)setSelected(index);},[]);
 const p=projects[selected];const jacket=jackets[selected];
 async function share(){const url=new URL(location.href);url.searchParams.set('project',p.id);url.hash='work';try{await navigator.clipboard.writeText(url.href);setShareStatus('Project link copied.');}catch{setShareStatus('Copy the page address to share this project.');}}
 function choose(index:number,fromKeyboard=false,reveal=false){const next=(index+projects.length)%projects.length;setKeyboard(fromKeyboard);setSelected(next);setShareStatus('');const url=new URL(location.href);url.searchParams.set('project',projects[next].id);history.replaceState(null,'',url);if(reveal){const quiet=matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.motion==='off';document.getElementById('screening-room')?.scrollIntoView({behavior:quiet?'instant':'smooth',block:'start'});}}
 return <section id="work" className="cinema-work" aria-labelledby="cinema-title">
 <div className="cinema-heading"><div><span className="eyebrow">THE ATHENA COLLECTION</span><h2 id="cinema-title">Pick a story.<br/><em>See where it goes.</em></h2></div><div className="collection-intro"><p>Products, experiments, and the thinking in between. A collection of things I’ve put into the world.</p><div className="collection-views" aria-label="Collection view"><button aria-pressed={!map} onClick={()=>setMap(false)}><Disc3 size={16}/>The shelf</button><button aria-pressed={map} onClick={()=>setMap(true)}><Network size={16}/>The connections</button></div></div></div>
 {!map?<><div className="film-shelf" ref={shelf} aria-label="Choose a project" onKeyDown={e=>{if(e.key!=='ArrowRight'&&e.key!=='ArrowLeft'&&e.key!=='Home'&&e.key!=='End')return;e.preventDefault();const i=e.key==='Home'?0:e.key==='End'?5:(selected+(e.key==='ArrowRight'?1:5))%6;choose(i,true);shelf.current?.querySelectorAll('button')[i]?.focus();}}>{projects.map((project,i)=><button key={project.id} className={`film-jacket ${selected===i?'is-selected':''}`} style={{'--jacket':jackets[i].color,'--jacket-ink':jackets[i].ink} as CSSProperties} aria-pressed={selected===i} aria-controls="screening-room" onClick={e=>choose(i,e.detail===0,true)}><span className="jacket-spine">{project.name}</span><span className="jacket-face"><span className="jacket-edition">ATHENA HUO / SELECTED WORK</span><strong>{jackets[i].title}</strong><span className="jacket-art">{jackets[i].image?<img src={`/previews/${jackets[i].image}`} alt="" loading="lazy"/>:<WorkflowArt index={i}/>}</span><span className="jacket-name">{project.name}<ArrowUpRight size={15}/></span><span className="jacket-sub">{jackets[i].sub}</span></span></button>)}</div><div className="shelf-caption"><span>Choose a sleeve to open its story.</span><span>← → Browse the collection</span></div></>:<div className="connection-view"><div className="connection-map" aria-label="Projects connected by shared ideas"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{connections.map(c=><line key={c.label} x1={points[c.a][0]} y1={points[c.a][1]} x2={points[c.b][0]} y2={points[c.b][1]} className={c.a===selected||c.b===selected?'line-active':''}/>)}</svg><span className="map-center">A useful idea<br/><em>rarely stays in one place.</em></span>{projects.map((project,i)=><button key={project.id} style={{left:`${points[i][0]}%`,top:`${points[i][1]}%`,'--jacket':jackets[i].color,'--jacket-ink':jackets[i].ink} as CSSProperties} className={`map-node ${selected===i?'is-selected':''}`} aria-pressed={selected===i} aria-controls="screening-room" onClick={e=>choose(i,e.detail===0)}>{project.name}<ArrowUpRight size={13}/></button>)}</div><div className="connection-notes"><span className="eyebrow">FOLLOW THE THREAD / {p.name}</span>{connections.filter(c=>c.a===selected||c.b===selected).map(c=><button key={c.label} onClick={e=>choose(c.a===selected?c.b:c.a,e.detail===0)}><strong>{c.label}<ArrowRight size={16}/></strong><span>{c.why}</span></button>)}</div></div>}
 <article id="screening-room" className={`screening-room ${keyboard?'keyboard-change':''}`} style={{'--scene-color':jacket.color,'--scene-ink':jacket.ink} as CSSProperties}>
 <div className="screening-bar"><span><i/> NOW SHOWING / <b aria-live="polite">{p.name}</b></span><div><span>{String(selected+1).padStart(2,'0')} / 06</span><button aria-label="Previous project" onClick={e=>choose(selected-1,e.detail===0)}><ArrowLeft size={18}/></button><button aria-label="Next project" onClick={e=>choose(selected+1,e.detail===0)}><ArrowRight size={18}/></button></div></div>
 <div className="scene" key={p.id}><div className="scene-screen">{projectPreviews[p.id]?<ProjectPreview preview={projectPreviews[p.id]}/>:<div className="scene-artwork"><WorkflowArt index={selected}/><span>WORKFLOW STUDY / {p.name.toUpperCase()}</span><h3>{jacket.title}</h3><p>{jacket.sub}</p></div>}</div><div className="scene-notes"><span className="eyebrow">{p.status}</span><h3>{p.headline}</h3><p>{p.summary}</p><div className="project-diagram" aria-label={p.stages.join(' to ')}>{p.stages.map((stage,i)=><div key={stage}><span className="stage-dot"/><span>{stage}</span>{i<3&&<ArrowRight size={16}/>}</div>)}</div><div className="scene-proof">{p.proof}{p.id==='athena-ai'&&<small>Founder-reported · résumé</small>}</div><div className="scene-actions"><Story p={p}/><a href={p.links.find(l=>!l.url.includes('github')&&!l.url.startsWith('/'))?.url??p.links[0].url} target="_blank" rel="noreferrer">{p.links.some(l=>!l.url.includes('github')&&!l.url.startsWith('/'))?'Visit project':'View source'}<ArrowUpRight size={16}/></a><button className="scene-share" onClick={share}><Link2 size={14}/>Copy project link</button></div><span className="scene-share-status" role="status">{shareStatus}</span></div></div>
 </article><a className="collection-resume" href="/AthenaHuo.pdf" target="_blank" rel="noreferrer">Prefer the one-page version? Read my résumé <ArrowUpRight size={16}/></a>
 </section>
}
