'use client';
import {useEffect,useRef} from 'react';
type Point={x:number;y:number;z:number;a:number};
const COUNT=540;
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
function point(i:number,form:number):Point{const u=(i+.5)/COUNT,angle=i*Math.PI*(3-Math.sqrt(5));if(form===0){const r=2+(i%17)/17;return{x:Math.cos(angle)*r,y:(u-.5)*5,z:Math.sin(angle)*r,a:.12};}if(form===1){const y=1-2*u,r=Math.sqrt(1-y*y);return{x:Math.cos(angle)*r,y,z:Math.sin(angle)*r,a:1};}const v=(i%29)/29*Math.PI*2,R=.86+.22*Math.cos(v);return{x:R*Math.cos(angle),y:.22*Math.sin(v),z:R*Math.sin(angle),a:1};}
const forms=[0,1,2,0].map(f=>Array.from({length:COUNT},(_,i)=>point(i,f)));
export default function ParticleStudio(){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{const el=canvas.current,section=el?.closest('section');if(!el||!section)return;const ctx=el.getContext('2d');if(!ctx)return;const mq=matchMedia('(prefers-reduced-motion: reduce)');let width=0,height=0,raf=0,visible=false,disposed=false;
 const paint=()=>{raf=0;if(disposed||!visible||document.hidden)return;ctx.clearRect(0,0,width,height);if(mq.matches||document.documentElement.dataset.motion==='off')return;const rect=section.getBoundingClientRect(),progress=clamp((innerHeight-rect.top)/(innerHeight+rect.height));const travel=clamp((progress-.08)/.84)*3,index=Math.min(2,Math.floor(travel)),t=travel-index;const a=forms[index],b=forms[index+1],fade=Math.sin(progress*Math.PI)*.75;const yaw=.25+progress*.85,pitch=-.4+progress*.2,cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch),scale=Math.min(width,height)*.3;
 const dots=a.map((p,i)=>{const x0=p.x+(b[i].x-p.x)*t,y0=p.y+(b[i].y-p.y)*t,z0=p.z+(b[i].z-p.z)*t,x=x0*cy-z0*sy,z1=x0*sy+z0*cy,y=y0*cx-z1*sx,z=y0*sx+z1*cx,d=3.7/(3.7+z);return{x:width*.5+x*scale*d,y:height*.5+y*scale*d,z,r:(i%7===0?2.2:1.2)*d,a:(p.a+(b[i].a-p.a)*t)*fade*(.55-z*.12),i};}).sort((a,b)=>b.z-a.z);
 for(const p of dots){ctx.globalAlpha=clamp(p.a);ctx.fillStyle=p.i%7===0?'#a78b2b':'#243b9b';ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.2,p.r),0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
 const request=()=>{if(!raf&&!disposed&&visible&&!document.hidden)raf=requestAnimationFrame(paint);};const resize=new ResizeObserver(entries=>{const r=entries[0].contentRect;width=r.width;height=r.height;const dpr=Math.min(devicePixelRatio||1,2);el.width=Math.round(width*dpr);el.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);request();});resize.observe(el);const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)request();else{cancelAnimationFrame(raf);raf=0;}},{threshold:0});intersection.observe(section);addEventListener('scroll',request,{passive:true});addEventListener('resize',request);addEventListener('portfolio-motion',request);mq.addEventListener('change',request);document.addEventListener('visibilitychange',request);return()=>{disposed=true;cancelAnimationFrame(raf);resize.disconnect();intersection.disconnect();removeEventListener('scroll',request);removeEventListener('resize',request);removeEventListener('portfolio-motion',request);mq.removeEventListener('change',request);document.removeEventListener('visibilitychange',request);};},[]);return <canvas ref={canvas} className="scroll-particles" aria-hidden="true"/>;}
