'use client';
import {useState} from 'react';
import ParticleStudio from './particle-studio';
import {ArrowUpRight,ArrowRight,Download,Plus,Minus,Camera} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {projects,experiments,type Project} from './projects';
function ExternalLink({url,children}:{url:string;children:React.ReactNode}){return <a href={url} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={17}/></a>}
function ProjectCard({project:p,index}:{project:Project;index:number}){return <Dialog><DialogTrigger className={`project-card project-${p.id} ${index<2?'project-wide':''}`}><div className="project-top"><span>{p.category}</span><ArrowUpRight size={23}/></div><div className="project-body"><div><span className="project-name">{p.name}</span><h3>{p.headline}</h3><p>{p.summary}</p></div><div className="project-diagram" aria-label={p.stages.join(' to ')}>{p.stages.map((s,i)=><div key={s}><span className="stage-dot"/><span>{s}</span>{i<3&&<ArrowRight size={16}/>}</div>)}</div></div><div className="project-bottom"><span>{p.proof}{p.id==='athena-ai'&&<small>Founder-reported · résumé</small>}</span><span className="read-story">Read the story <Plus size={18}/></span></div></DialogTrigger><DialogContent className="project-dialog"><div className="dossier-top"><span className="eyebrow">PROJECT NOTES / {p.name.toUpperCase()}</span><span className="status-label">{p.status}</span></div><DialogTitle className="dossier-title">{p.headline}</DialogTitle><DialogDescription className="dossier-deck">{p.summary}</DialogDescription><div className="dossier-sections"><section><h4>The problem</h4><p>{p.problem}</p></section><section><h4>What I built</h4><p>{p.built}</p></section><section><h4>The decision that matters</h4><p>{p.decision}</p></section><section className="evidence-note"><h4>What the evidence supports</h4><p>{p.boundary}</p></section></div><div className="stack-list">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="dossier-links">{p.links.map(l=><ExternalLink key={l.url} url={l.url}>{l.label}</ExternalLink>)}</div></DialogContent></Dialog>}
export function QuickRead(){return <Dialog><DialogTrigger className="quick-read">Have 60 seconds? <ArrowUpRight size={16}/></DialogTrigger><DialogContent className="project-dialog quick-dialog"><span className="eyebrow">ATHENA HUO / THE SHORT VERSION</span><DialogTitle className="dossier-title">I connect the technical work<br/>to the people it’s for.</DialogTitle><DialogDescription className="dossier-deck">I build useful products and bring people into the story. Based in New York.</DialogDescription><div className="quick-points"><section><strong>I can build it.</strong><p>Solo full-stack delivery at Whetstone, from role-based access and scheduling to a platform used by students, parents, and counselors.</p></section><section><strong>I can reason about it.</strong><p>Sports forecasting, grounded AI answers, and decision-support products that make uncertainty visible.</p></section><section><strong>I can get it in front of people.</strong><p>Athena.ai combines product ownership with daily short-form content. My résumé reports ~500 registered users in week one and organic account growth from 400 to 15,000.</p></section></div><p className="fit-line">I want to own the journey from a real problem to a product people use.</p><div className="dossier-links"><ExternalLink url="/AthenaHuo.pdf">Read the résumé</ExternalLink><a href="mailto:zhengathenahuo@gmail.com">Get in touch<ArrowUpRight size={17}/></a></div></DialogContent></Dialog>}
export function PortfolioSections(){const [more,setMore]=useState(false);return <>
<section id="work" className="work-section"><div className="section-heading"><span className="eyebrow">SELECTED WORK</span><h2>Different mediums.<br/><em>Same curiosity.</em></h2><p>The interesting part is usually where the disciplines meet.</p></div>
<div className="work-intro"><p>From understanding the problem to building something people use.</p><span>Six projects. The thinking behind each one.</span></div><div className="projects-grid">{projects.map((p,i)=><ProjectCard key={p.id} project={p} index={i}/>)}</div>
<div className="more-work"><div><span className="eyebrow">THE EXPLORATION CONTINUES</span><h3>Also on my workbench.</h3></div><button className="archive-toggle" aria-expanded={more} aria-controls="workbench" onClick={()=>setMore(!more)}>{more?'Close the workbench':'Open the workbench'}{more?<Minus size={20}/>:<Plus size={20}/>}</button></div><div id="workbench" hidden={!more}><div className="experiments-grid">{experiments.map(e=><a key={e.name} href={e.url} target="_blank" rel="noreferrer" className="experiment"><div><span>{e.type}</span><ArrowUpRight size={20}/></div><h4>{e.name}</h4><p>{e.description}</p></a>)}</div><p className="archive-note">A selected collection of prototypes, creative experiments, and supporting work. <a href="https://github.com/athenahz01" target="_blank" rel="noreferrer">The full GitHub archive ↗</a></p></div>
</section>
<section className="creator-section" id="other-side"><div className="creator-heading"><span className="eyebrow">THE OTHER SIDE / @ATHENA_HUO</span><h2>Yes, I also<br/><em>make the content.</em></h2><p>Short-form stories and a life outside the code editor. Creating gives me another way to think about attention, clarity, and what people connect with.</p><ExternalLink url="https://www.instagram.com/athena_huo/">Find me on Instagram<Camera size={18}/></ExternalLink></div><ParticleStudio/><div className="creator-bridge"><span>BUILD ↔ TELL ↔ LISTEN ↔ BUILD</span><p>Spool and Mira come from this side of my life. So does the instinct to think about distribution while I’m building.</p></div></section>
<section className="about-section" id="about"><div className="about-heading"><span className="eyebrow">A LITTLE CONTEXT</span><h2>I’m comfortable<br/><em>between worlds.</em></h2><p>I studied Data Science at Berkeley and Systems Engineering at Cornell. My work has taken me from revenue analysis and client research to shipping products and building an audience.</p><p>I’m drawn to work that needs both: someone who can understand the problem with people, then stay close enough to the implementation to make it real.</p><QuickRead/></div><div className="experience-list"><article><div><h3>Athena.ai</h3><span>JUN 2026 — PRESENT</span></div><h4>Founder</h4><p>Forecasting models, product delivery, and organic distribution.</p></article><article><div><h3>Whetstone Admissions</h3><span>MAR 2026 — PRESENT</span></div><h4>Operations Analyst</h4><p>Full-stack admissions platform and delivery across company products.</p></article><article><div><h3>CVS Health × Cornell</h3><span>JAN — MAY 2026</span></div><h4>Product Strategy Consultant</h4><p>20 interviews, 768 survey responses, and a segmentation analysis of 601 students to inform the college shopping strategy.</p></article><article><div><h3>Plug and Play</h3><span>NOV 2024 — MAR 2025</span></div><h4>Data Analyst</h4><p>Revenue analysis across 10+ verticals, six Salesforce dashboards, and cross-team operational reporting.</p></article><div className="education"><span>Cornell · M.Eng., Systems Engineering · 2026</span><span>UC Berkeley · B.A., Data Science · 2025</span></div></div></section>
<footer className="contact-section"><span className="eyebrow">SOMETHING INTERESTING IN MIND?</span><a className="contact-title" href="mailto:zhengathenahuo@gmail.com">Let’s make<br/><em>something matter.</em><ArrowUpRight/></a><div className="contact-bottom"><a href="mailto:zhengathenahuo@gmail.com">zhengathenahuo@gmail.com</a><div><ExternalLink url="/AthenaHuo.pdf">Résumé<Download size={15}/></ExternalLink><ExternalLink url="https://github.com/athenahz01">GitHub</ExternalLink><ExternalLink url="https://www.linkedin.com/in/athena-huo/">LinkedIn</ExternalLink><ExternalLink url="https://www.instagram.com/athena_huo/">Instagram</ExternalLink></div></div><div className="colophon"><span>ATHENA HUO © 2026</span><span>Made of more than one thing.</span><a href="#top">Back to top ↑</a></div></footer></>}




